config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new' 
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
      member do
          get :following, :followers
      end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="#">Soc set</a>
        by <a href="#">FreezkoS</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "Наша команда", about_path %></li>
            <li><%= link_to "Контанкты", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="nav navbar-fixed-top navbar-inverse">
          <div class="container">
             <div class="row">
              <nav class="bg_nav">
                  <div class="col-md-6 col-12">
                      <div class="save">
                        <%= link_to image_tag("logo.png", :id => 'logo'), root_path %>
                      </div>
                      </div>
                   <div class="col-md-6">
                  <ul class="nav navbar-nav navbar-right">
                      <li><%= link_to "Главная", root_path %>
                      <li><%= link_to "Помощь", help_path %>
                      <% if logged_in? %>
                        <li><%= link_to "Хлопцы", users_path %></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Аккаунт <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Профиль", current_user %></li>
                                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                                <li class="divider"></li>
                                <li>
                                <%= link_to "Выход", logout_path, method: "delete" %>
                                </li>
                            </ul>
                        </li>
                      <% else %>
                      <li><%= link_to "Войти", login_path %>
                      <% end %>
                  </ul>
                  </div>
              </nav>
                 </div>
          </div>
      </header>

app/views/layouts/_shim.html.erb
<!--[if it IE9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container pr">
    
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
          
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>